# Generated by Django 3.1 on 2021-04-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_auto_20210422_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(default=0),
        ),
    ]
